BAT_SPEED = 2
PRINT_PATH = True
NUM_OBSTABLES = 40
MARGIN_NO_OBSTICLE = 20
REWARD_HIT_TREE = -2
REWARD_MOVE = -0.3
REWARD_BETTER_DISTANCE = 0.8
REWARD_ON_EDGE = -1
REWARD_GOAL = 30
GAMMA = 0.8

OUTPUT_FILE = 'tmp.csv'
MODEL_FILE = 'tmp_brain.pth'
