BAT_SPEED = 2
PRINT_PATH = True
NUM_OBSTABLES = 20
MARGIN_NO_OBSTICLE = 20
REWARD_HIT_TREE = -1  # -1
REWARD_MOVE = -0.2
REWARD_BETTER_DISTANCE = 0.1
REWARD_ON_EDGE = -1
REWARD_GOAL = 2  # 5
GAMMA = 0.95

OUTPUT_FILE = 'tmp.csv'
MODEL_FILE = 'tmp_brain.pth'

LEARNING_RATE = 0.0001
BATCH_SIZE = 200
